apiVersion: v1
kind: Service
metadata:
  name: build
  labels:
    app: build
spec:
  ports:
  - port: 8996
    protocol: TCP
  clusterIP: None
  selector:
    app: build
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: build
  labels:
    app: build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build
  template:
    metadata:
      labels:
        app: build
    spec:
      containers:
      - name: build
        image: build
        env:
          - name: OLLAMA_SERVER
            value: "http://ollama:11434"
